nelmio_api_doc:
    documentation:
        info:
            title: KRRU IDM API
            description: KRRU Lan Management System IDM API
            version: 0.9.1
        securityDefinitions:
            apiKey:
                type: apiKey
                description: 'Value: {apiKey}'
                name: X-API-KEY
                in: header
        security:
            - apiKey: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc|/doc.json$) # Accepts routes under /api except /api/doc
